name: Build RM520 Unix Release

on:
  #push:
  # pull_request:
  #   paths:
  #     - '.github/workflows/*.yml'
  #     - 'tools/**'
  #     - 'py/**'
  #     - 'extmod/**'
  #     - 'shared/**'
  #     - 'lib/**'
  #     - 'examples/**'
  #     - 'mpy-cross/**'
  #     - 'ports/unix/**'
  #     - 'tests/**'
  workflow_dispatch:
  release:
    types:
      - created

permissions: write-all

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

jobs:
  build_qemu_arm_rm520:
    runs-on: ubuntu-20.04

    steps:

    - name: checkout code
      uses: actions/checkout@v3

    # Build the mpy cross-compiler
    - name: Setup build environment
      run: source tools/ci.sh && ci_unix_qemu_arm_setup

    - name: Cross-compile for arm
      run: source tools/ci.sh && ci_unix_qemu_arm_build

    - name: Install patchelf
      run: sudo apt-get install patchelf

    - name: Fix interpreter
      run: patchelf --set-interpreter /lib/ld-linux-armhf.so.3 ports/unix/build-standard/micropython

    - name: Fix needed libs
      run: patchelf --replace-needed ld-linux.so.3 ld-linux-armhf.so.3 ports/unix/build-standard/micropython

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ports/unix/build-standard/micropython
        asset_name: micropython.rm520
        tag: ${{ github.ref }}
        overwrite: true
        body: "Micropython ARM binary for Quectel RM520"

  build_qemu_arm_rm50x:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:18.04

    steps:

    # Updated git repo
    - name: Install git ppa
      run: apt-get update && apt-get install -y software-properties-common && add-apt-repository ppa:git-core/ppa && apt-get update && apt-get install git=1:2.41.0-0ppa1~ubuntu18.04.1
      shell: bash

    # Install sudo, git, etc.
    - name: Install sudo
      run: apt-get update && apt-get install -y sudo bash build-essential git libffi-dev pkg-config patchelf file apt ca-certificates curl wget vim ssh python3

    - name: checkout code
      uses: actions/checkout@v3

    # Build the mpy cross-compiler
    - name: Setup build environment
      run: source tools/ci.sh && ci_unix_qemu_arm_setup
      shell: bash

    - name: Cross-compile for arm
      run: source tools/ci.sh && ci_unix_qemu_arm_build
      shell: bash

    - name: Install patchelf
      run: sudo apt-get install patchelf
      shell: bash

    - name: Fix interpreter
      run: patchelf --set-interpreter /lib/ld-linux-armhf.so.3 ports/unix/build-standard/micropython
      shell: bash

    - name: Fix needed libs
      run: patchelf --replace-needed ld-linux.so.3 ld-linux-armhf.so.3 ports/unix/build-standard/micropython
      shell: bash

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ports/unix/build-standard/micropython
        asset_name: micropython.rm50x
        tag: ${{ github.ref }}
        overwrite: true
        body: "Micropython ARM binary for Quectel RM50x"
