name: Build RM520 Unix Release

on:
  #push:
  # pull_request:
  #   paths:
  #     - '.github/workflows/*.yml'
  #     - 'tools/**'
  #     - 'py/**'
  #     - 'extmod/**'
  #     - 'shared/**'
  #     - 'lib/**'
  #     - 'examples/**'
  #     - 'mpy-cross/**'
  #     - 'ports/unix/**'
  #     - 'tests/**'
  workflow_dispatch:
  release:
    types:
      - created

permissions: write-all

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

jobs:
  build_qemu_arm:
    runs-on: ubuntu-20.04

    steps:

    - name: checkout code
      uses: actions/checkout@v3

    # Build the mpy cross-compiler
    - name: Setup build environment
      run: source tools/ci.sh && ci_unix_qemu_arm_setup

    - name: Cross-compile for arm
      run: source tools/ci.sh && ci_unix_qemu_arm_build

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ports/unix/build-coverage/micropython
        asset_name: micropython.rm520
        tag: ${{ github.ref }}
        overwrite: true
        body: "Micropython ARM binary for Quectel RM520"
